version: "3"

services:
  wordpress:
    build: ./wordpress_xdebug
    image: wordpress-xdebug
    container_name: woocommerce_rave
    restart: always
    depends_on:
      - db
    links:
      - db:mysql
    ports:
      - "8080:80"
    env_file:
      - config/default.env
    volumes:
      - ./wordpress:/var/www/html/
      - ./logs/apache2/:/var/log/apache2
      - ./../:/var/www/html/wp-content/plugins/woocommerce-rave
      - ./../tests/phpunit:/var/www/html/wp-content/plugins/woocommerce-rave/tests/PHPUnit
      - ./php/dev-php.ini:/usr/local/etc/php/conf.d/dev-php.ini
      - ./bin:/var/scripts
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    container_name: woocommerce_rave_mysql
    image: mariadb:10.5.8
    ports:
      - "5678:3306"
    env_file:
      - config/default.env
    volumes:
      - ./data:/var/lib/mysql
  phpMyAdmin:
    container_name: woocommerce_rave_phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8083:80"
    env_file:
      - config/default.env